/*****************************************************************************
 *
 *
 * Copyright 2016 - 2023 CHENGDU HAIGUANG IC DESIGN CO., LTD. All Rights Reserved.
 *
 * HYGON is granting you permission to use this software (the Materials)
 * pursuant to the terms and conditions of your Software License Agreement
 * with HYGON.  This header does *NOT* give you permission to use the Materials
 * or any rights under HYGON's intellectual property.  Your use of any portion
 * of these Materials shall constitute your acceptance of those terms and
 * conditions.  If you do not agree to the terms and conditions of the Software
 * License Agreement, please do not use any portion of these Materials.
 *
 * CONFIDENTIALITY:  The Materials and all other information, identified as
 * confidential and provided to you by HYGON shall be kept confidential in
 * accordance with the terms and conditions of the Software License Agreement.
 *
 * LIMITATION OF LIABILITY: THE MATERIALS AND ANY OTHER RELATED INFORMATION
 * PROVIDED TO YOU BY HYGON ARE PROVIDED "AS IS" WITHOUT ANY EXPRESS OR IMPLIED
 * WARRANTY OF ANY KIND, INCLUDING BUT NOT LIMITED TO WARRANTIES OF
 * MERCHANTABILITY, NONINFRINGEMENT, TITLE, FITNESS FOR ANY PARTICULAR PURPOSE,
 * OR WARRANTIES ARISING FROM CONDUCT, COURSE OF DEALING, OR USAGE OF TRADE.
 * IN NO EVENT SHALL HYGON OR ITS LICENSORS BE LIABLE FOR ANY DAMAGES WHATSOEVER
 * (INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF PROFITS, BUSINESS
 * INTERRUPTION, OR LOSS OF INFORMATION) ARISING OUT OF HYGON'S NEGLIGENCE,
 * GROSS NEGLIGENCE, THE USE OF OR INABILITY TO USE THE MATERIALS OR ANY OTHER
 * RELATED INFORMATION PROVIDED TO YOU BY HYGON, EVEN IF HYGON HAS BEEN ADVISED OF
 * THE POSSIBILITY OF SUCH DAMAGES.  BECAUSE SOME JURISDICTIONS PROHIBIT THE
 * EXCLUSION OR LIMITATION OF LIABILITY FOR CONSEQUENTIAL OR INCIDENTAL DAMAGES,
 * THE ABOVE LIMITATION MAY NOT APPLY TO YOU.
 *
 * HYGON does not assume any responsibility for any errors which may appear in
 * the Materials or any other related information provided to you by HYGON, or
 * result from use of the Materials or any related information.
 *
 * You agree that you will not reverse engineer or decompile the Materials.
 *
 * NO SUPPORT OBLIGATION: HYGON is not obligated to furnish, support, or make any
 * further information, software, technical information, know-how, or show-how
 * available to you.  Additionally, HYGON retains the right to modify the
 * Materials at any time, without notice, and is not obligated to provide such
 * modified Materials to you.
 *
 *
 *
 ***************************************************************************/

// This file is auto generated, don't edit it manually

#ifndef _IDS_NV_ID_SAT_H_
#define _IDS_NV_ID_SAT_H_

typedef enum {
  IDS_NVID_START = 0x0000,
// Dharma Common Options
  IDSNVID_CMN_CPU_PFEH,
  IDSNVID_CMN_CPU_CPB,
  IDSNVID_CMN_CPU_EN_IBS,
  IDSNVID_CMN_CPU_CSTATE_CTRL,
  IDSNVID_CMN_CPU_OPCACHE_CTRL,
  IDSNVID_CMN_CPU_OC_MODE,
  IDSNVID_CMN_CPU_CSV_ASID_SPACE_LIMIT,
  IDSNVID_CMN_CPU_STREAMING_STORES_CTRL,
  IDSNVID_CMN_CPU_RDSEED_RDRAND_CTRL,
  IDSNVID_CMN_CPU_LOAD_UCODE_CONTROL,
  IDSNVID_CMN_CPU_DISPLAY_RDRAND_RDSEED,
  IDSNVID_CMN_CPU_SMEE_CONTROL,
  IDSNVID_CMN_CPU_SMEE_CAP_CONTROL,
  IDSNVID_CMN_CPU_SVM_CONTROL,
  IDSNVID_CMN_CPU_FORCE_VDDCR_CPU_VID_EN,
  IDSNVID_CMN_CPU_FORCE_VDDCR_CPU_VID,
  IDSNVID_CMN_CPU_VDDCR_CPU_VOLTAGE_MARGIN  ,
  IDSNVID_CMN_CPU_FORCE_CCLK_FREQUENCY_EN,
  IDSNVID_CMN_CPU_FORCE_CCLK_FREQUENCY,
  IDSNVID_CMN_CPU_DLDO_BYPASS,
  IDSNVID_CMN_CPU_WATCHDOG_CTRL,
  IDSNVID_CMN_CPU_LAPIC_MODE,
  IDSNVID_CMN_SMT_MODE_CTRL,
  IDSNVID_CMN_CPU_ABOVE4G_MMIO_LIMIT_BIT,

// Custom Core Pstates
  IDSNVID_CPU_LEGAL_DISCLAIMER,
  IDSNVID_CPU_LEGAL_DISCLAIMER1,
// Decline
// Accept
  IDSNVID_CPU_PST_CUSTOM_P0,
  IDSNVID_CPU_COF_P0,
  IDSNVID_CPU_VOLTAGE_P0,
  IDSNVID_CPU_PST0_FID,
  IDSNVID_CPU_PST0_DID,
  IDSNVID_CPU_PST0_VID,
  IDSNVID_CPU_PST_CUSTOM_P1,
  IDSNVID_CPU_COF_P1,
  IDSNVID_CPU_VOLTAGE_P1,
  IDSNVID_CPU_PST1_FID,
  IDSNVID_CPU_PST1_DID,
  IDSNVID_CPU_PST1_VID,
  IDSNVID_CPU_PST_CUSTOM_P2,
  IDSNVID_CPU_COF_P2,
  IDSNVID_CPU_VOLTAGE_P2,
  IDSNVID_CPU_PST2_FID,
  IDSNVID_CPU_PST2_DID,
  IDSNVID_CPU_PST2_VID,

// Disagree
// Agree
  IDSNVID_CMN_CPU_GEN_DOWNCORE_CTRL,
// Prefetcher settings
  IDSNVID_CMN_CPU_L1_STREAM_HW_PREFETCHER,
  IDSNVID_CMN_CPU_L2_STREAM_HW_PREFETCHER,
// DF Common Options
  IDSNVID_DF_CMN_DRAM_SCRUB_TIME,
  IDSNVID_DF_CMN_REDIR_SCRUB_CTRL,
  IDSNVID_DF_CMN_SYNC_FLOOD_PROP,
  IDSNVID_DF_CMN_FREEZE_QUEUE_ERROR,
  IDSNVID_DF_CMN_HMI_ENCRYPTION,
  IDSNVID_DF_CMN_X_HMI_ENCRYPTION,
  IDSNVID_DF_CMN_CC6_MEM_ENCRYPTION,
  IDSNVID_DF_CMN_CC6_ALLOCATION_SCHEME,
  IDSNVID_DF_CMN_SYS_PROBE_FILTER,
  IDSNVID_DF_CMN_MEM_INTLV,
  IDSNVID_DF_CMN_MEM_INTLV_SIZE,
  IDSNVID_DF_CMN_CHNL_INTLV_HASH,
  IDSNVID_DF_CMN_MEM_CLEAR,
// UMC Common Options
// DDR5 Common Options
// DRAM Timing Configuration
  IDSNVID_CMN_MEM_TIMING_LEGAL_DISCLAIMER,
  IDSNVID_CMN_MEM_TIMING_LEGAL_DISCLAIMER1  ,
// I Decline
// I Accept
  IDSNVID_CMN_MEM_OVERCLOCK_DDR5,
  IDSNVID_CMN_MEM_SPEED_DDR5,
// DRAM Controller Configuration
  IDSNVID_CMN_MEM_CTRLLER2_T_MODE_DDR5,
  IDSNVID_CMN_MEM_GEAR_DOWN_MODE_DDR5,
// DRAM Power Options
  IDSNVID_CMN_MEM_CTRLLER_PWR_DN_EN_DDR5,
// Data Bus Configuration
  IDSNVID_CMN_MEM_DATA_BUS_CONFIG_CTL_DDR5  ,
  IDSNVID_CMN_MEM_CTRLLER_RTT_NOM_DDR5,
  IDSNVID_CMN_MEM_CTRLLER_RTT_WR_DDR5,
  IDSNVID_CMN_MEM_CTRLLER_RTT_PARK_DDR5,
// Common RAS
  IDSNVID_CMN_MEM_DATA_POISONING_DDR5,
// ECC Configuration
  IDSNVID_CMN_MEM_CTRLLER_DRAM_ECC_SYMBOL_SIZE_DDR5  ,
  IDSNVID_CMN_MEM_CTRLLER_DRAM_ECC_EN_DDR5,
// Security
  IDSNVID_CMN_MEM_TSME_DDR5,
  IDSNVID_CMN_MEM_CTRLLER_DATA_SCRAMBLE_DDR5,
// DRAM Memory Mapping
  IDSNVID_CMN_MEM_MAPPING_BANK_INTERLEAVE_DDR5,
  IDSNVID_CMN_MEM_CTRLLER_BANK_GROUP_SWAP_DDR5,
  IDSNVID_CMN_MEM_ADDRESS_HASH_BANK_DDR5,
  IDSNVID_CMN_MEM_ADDRESS_HASH_CS_DDR5,
// Memory MBIST
  IDSNVID_CMN_MEM_MBIST_EN,
  IDSNVID_CMN_MEM_MBIST_TESTMODE,
  IDSNVID_CMN_MEM_MBIST_AGGRESSORS,
  IDSNVID_CMN_MEM_MBIST_PER_BIT_SLAVE_DIE_REPORT,
// NBIO Common Options
  IDSNVID_CMN_GNB_SMU_SYSTEM_CONFIG,
  IDSNVID_DBG_POISON_CONSUMPTION,
  IDSNVID_NBIO_RAS_CONTROL,
  IDSNVID_CMNC_TDP_CTL,
  IDSNVID_CMNC_TDP_LIMIT,
  IDSNVID_CMN_TDP_BOOST,
  IDSNVID_CMN_NBIO_EFFICIENCY_OPTIMIZED_MODE,
  IDSNVID_CMN_NBIO_PSI_DISABLE,
  IDSNVID_DBG_GNB_DBG_ACS_ENABLE,
  IDSNVID_GNB_DBG_PCIE_ARI_SUPPORT,
  IDSNVID_CMN_CLDO_VDDP_CTL,
  IDSNVID_CMN_CLDOVDD_PVOLTAGE,
  IDSNVID_CMN_GNB_HD_AUDIO_EN,
  IDSNVID_CFG_PCIE_LOOPBACK_MODE,
  IDSNVID_CFG_PCIE_CRS_DELAY,
  IDSNVID_CFG_PCIE_CRS_LIMIT,
// NB Configuration
  IDSNVID_CMN_GNB_NB_IOMMU,
  IDSNVID_PCIE_SYNC_RESET,
  IDSNVID_XHMI_LINK_WIDTH,
  IDSNVID_TCDX_ROUTING_METHOD,
  IDSNVID_PCIE_EQ_MODE,
  IDSNVID_PCIE_4SYMBOL,
  IDSNVID_PCIE_ASPM_CONTROL,

// Hot Plug flags
  IDSNVID_CMN_DISABLE_SIDEBAND,
  IDSNVID_CMN_DISABLE_L1WA,
  IDSNVID_CMN_DISABLE_BRIDGE_DIS,
  IDSNVID_CMN_DISABLE_IRQ_POLL,
  IDSNVID_CMN_IRQ_SETS_BRIDGE_DIS,
// FCH Common Options
// SATA Configuration Options
  IDSNVID_CMN_FCH_SATA_ENABLE0,
  IDSNVID_CMN_FCH_SATA_ENABLE1,
  IDSNVID_CMN_FCH_SATA_ENABLE2,
  IDSNVID_CMN_FCH_SATA_ENABLE3,
  IDSNVID_CMN_FCH_SATA_CLASS,
  IDSNVID_CMN_FCH_SATA_RAS_SUPPORT,
  IDSNVID_CMN_FCH_SATA_AHCI_DIS_PREFETCH_FUNCTION,
  IDSNVID_DBG_FCH_SATA_AGGRESIVE_DEV_SLP_P0,
  IDSNVID_DBG_FCH_SATA_DEV_SLP_PORT0_NUM,
  IDSNVID_DBG_FCH_SATA_AGGRESIVE_DEV_SLP_P1,
  IDSNVID_DBG_FCH_SATA_DEV_SLP_PORT1_NUM,
// USB Configuration Options
  IDSNVID_CMN_FCH_USB_XHC_I0_ENABLE,
// MCM USB enable
  IDSNVID_CMN_FCH_USB_XHC_I1_ENABLE,
  IDSNVID_CMN_FCH_USB_XHC_I2_ENABLE,
  IDSNVID_CMN_FCH_USB_XHC_I3_ENABLE,
// I2C Configuration Options
  IDSNVID_CMN_FCH_I2_C0_CONFIG,
  IDSNVID_CMN_FCH_I2_C1_CONFIG,
  IDSNVID_CMN_FCH_I2_C2_CONFIG,
  IDSNVID_CMN_FCH_I2_C3_CONFIG,
  IDSNVID_CMN_FCH_I2_C4_CONFIG,
  IDSNVID_CMN_FCH_I2_C5_CONFIG,
  IDSNVID_CMN_FCH_I3_C0_CONFIG,
  IDSNVID_CMN_FCH_I3_C1_CONFIG,
// Uart Configuration Options
  IDSNVID_CMN_FCH_UART0_CONFIG,
  IDSNVID_CMN_FCH_UART0_LEGACY_CONFIG,
  IDSNVID_CMN_FCH_UART1_CONFIG,
  IDSNVID_CMN_FCH_UART1_LEGACY_CONFIG,
  IDSNVID_CMN_FCH_UART2_CONFIG,
  IDSNVID_CMN_FCH_UART2_LEGACY_CONFIG,
  IDSNVID_CMN_FCH_UART3_CONFIG,
  IDSNVID_CMN_FCH_UART3_LEGACY_CONFIG,
// NTB Common Options
  IDSNVID_CMN_NTB_ENABLE,
  IDSNVID_CMN_NTB_LOCATION,
  IDSNVID_CMN_NTB_PCIE_CORE_INDEX,
  IDSNVID_CMN_NTB_MODE,
  IDSNVID_CMN_NTB_LINK_SPEED,
  IDSNVID_DBG_S_P3_NTB_BAR1_SIZE,
  IDSNVID_DBG_S_P3_NTB_BAR23_SIZE,
  IDSNVID_DBG_S_P3_NTB_BAR45_SIZE,

  IDSNVID_CBS_PCIE_HOTPLUG_SUPPORT,
  IDSNVID_CMN_DF_CSTATE_CTRL,

// Validation Common Options
  IDSNVID_CBS_VALIDATION_DDR_PATRITY,
  IDSNVID_CBS_VALIDATION_PSPCCP_VQ_COUNT,

// USB Configuration Options
  IDSNVID_CMN_FCH_USB_XHC_I4_ENABLE,
  IDSNVID_CMN_FCH_USB_XHC_I5_ENABLE,
  IDSNVID_CMN_FCH_USB_XHC_I6_ENABLE,
  IDSNVID_CMN_FCH_USB_XHC_I7_ENABLE,

  IDS_NVID_END = 0xfffffffful,  // End of IDS NV ID
} IDSNVID_DEF;

#endif //_IDS_NV_ID_SAT_H_
