/*****************************************************************************
 *
 *
 * Copyright 2016 - 2023 CHENGDU HAIGUANG IC DESIGN CO., LTD. All Rights Reserved.
 *
 * HYGON is granting you permission to use this software (the Materials)
 * pursuant to the terms and conditions of your Software License Agreement
 * with HYGON.  This header does *NOT* give you permission to use the Materials
 * or any rights under HYGON's intellectual property.  Your use of any portion
 * of these Materials shall constitute your acceptance of those terms and
 * conditions.  If you do not agree to the terms and conditions of the Software
 * License Agreement, please do not use any portion of these Materials.
 *
 * CONFIDENTIALITY:  The Materials and all other information, identified as
 * confidential and provided to you by HYGON shall be kept confidential in
 * accordance with the terms and conditions of the Software License Agreement.
 *
 * LIMITATION OF LIABILITY: THE MATERIALS AND ANY OTHER RELATED INFORMATION
 * PROVIDED TO YOU BY HYGON ARE PROVIDED "AS IS" WITHOUT ANY EXPRESS OR IMPLIED
 * WARRANTY OF ANY KIND, INCLUDING BUT NOT LIMITED TO WARRANTIES OF
 * MERCHANTABILITY, NONINFRINGEMENT, TITLE, FITNESS FOR ANY PARTICULAR PURPOSE,
 * OR WARRANTIES ARISING FROM CONDUCT, COURSE OF DEALING, OR USAGE OF TRADE.
 * IN NO EVENT SHALL HYGON OR ITS LICENSORS BE LIABLE FOR ANY DAMAGES WHATSOEVER
 * (INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF PROFITS, BUSINESS
 * INTERRUPTION, OR LOSS OF INFORMATION) ARISING OUT OF HYGON'S NEGLIGENCE,
 * GROSS NEGLIGENCE, THE USE OF OR INABILITY TO USE THE MATERIALS OR ANY OTHER
 * RELATED INFORMATION PROVIDED TO YOU BY HYGON, EVEN IF HYGON HAS BEEN ADVISED OF
 * THE POSSIBILITY OF SUCH DAMAGES.  BECAUSE SOME JURISDICTIONS PROHIBIT THE
 * EXCLUSION OR LIMITATION OF LIABILITY FOR CONSEQUENTIAL OR INCIDENTAL DAMAGES,
 * THE ABOVE LIMITATION MAY NOT APPLY TO YOU.
 *
 * HYGON does not assume any responsibility for any errors which may appear in
 * the Materials or any other related information provided to you by HYGON, or
 * result from use of the Materials or any related information.
 *
 * You agree that you will not reverse engineer or decompile the Materials.
 *
 * NO SUPPORT OBLIGATION: HYGON is not obligated to furnish, support, or make any
 * further information, software, technical information, know-how, or show-how
 * available to you.  Additionally, HYGON retains the right to modify the
 * Materials at any time, without notice, and is not obligated to provide such
 * modified Materials to you.
 *
 *
 *
 ***************************************************************************/

// This file is auto generated, don't edit it manually

#ifndef _HPCB_AUTOGEN_SAT_H_
#define _HPCB_AUTOGEN_SAT_H_
#include "..\..\Inc\HPCB.h"
//
//
// HPCB Token Value Definition
//
#define HPCB_TOKEN_CBS_CMN_CPU_CSV_ASID_SPACE_LIMIT_VALUE    1
#define HPCB_TOKEN_CBS_CMN_MEM_TIMING_TRC_DDR5_VALUE         0x39
#define HPCB_TOKEN_CBS_CMN_MEM_TIMING_TFAW_DDR5_VALUE        26
#define HPCB_TOKEN_CBS_CMN_MEM_TIMING_TWR_DDR5_VALUE         18
#define HPCB_TOKEN_CBS_CMN_MEM_TIMING_TRCPAGE_DDR5_VALUE     0
#define HPCB_TOKEN_CBS_CMN_MEM_TIMING_TRDRD_SC_L_DDR5_VALUE  3
#define HPCB_TOKEN_CBS_CMN_MEM_TIMING_TWRWR_SC_L_DDR5_VALUE  0x3
#define HPCB_TOKEN_CBS_CMN_MEM_TIMING_TRFC_DDR5_VALUE        0x138
#define HPCB_TOKEN_CBS_CMN_MEM_TIMING_TRFC2_DDR5_VALUE       0xC0
#define HPCB_TOKEN_CBS_CMN_MEM_TIMING_TRFC4_DDR5_VALUE       0x84
#define HPCB_TOKEN_CBS_CMN_MEM_MBIST_EN_VALUE                0
#define HPCB_TOKEN_CBS_CMN_MEM_MBIST_SUB_TEST_VALUE          0
#define HPCB_TOKEN_CBS_CMN_CLDOVDD_PVOLTAGE_VALUE            0
#define HPCB_TOKEN_CBS_CMN_DJ_CLDO_VDDP_CTL_VALUE            0
#define HPCB_TOKEN_CBS_CMN_DJ_CLDOVDD_PVOLTAGE_VALUE         0x0
#define HPCB_TOKEN_CBS_CMN_EM_CLDO_VDDP_CTL_VALUE            0
#define HPCB_TOKEN_CBS_CMN_EM_CLDOVDD_PVOLTAGE_VALUE         0x00010000
#define HPCB_TOKEN_CBS_CMN_CDD_CLDO_VDDP_CTL_VALUE           0
#define HPCB_TOKEN_CBS_CMN_CDD_CLDOVDD_PVOLTAGE_VALUE        0x00020000
#define HPCB_TOKEN_CBS_CMN_CLDO_VDDM_CTL_VALUE               0
#define HPCB_TOKEN_CBS_CMN_CLDOVDD_MVOLTAGE_VALUE            0x0
#define HPCB_TOKEN_CBS_CMN_GNB_XHMI_PHY_RATE_CFG_VALUE       0xFF
#define HPCB_TOKEN_CBS_CMN_GNB_HMI_PHY_RATE_CFG_VALUE        0xFF
#define HPCB_TOKEN_CBS_CMN_FCH_CONSOLE_OUT_ENABLE_VALUE      0x1
#define HPCB_TOKEN_CBS_CMN_FCH_CONSOLE_OUT_DIE_TYPE_VALUE    0x2
#define HPCB_TOKEN_CBS_CMN_FCH_CONSOLE_OUT_SOCKET_ID_VALUE   0x0
#define HPCB_TOKEN_CBS_CMN_FCH_CONSOLE_OUT_IOD_ID_VALUE      0x0
#define HPCB_TOKEN_CBS_CMN_FCH_CONSOLE_OUT_CDD_ID_VALUE      0x0
#define HPCB_TOKEN_CBS_CMN_TPCM_CONTROL_VALUE                0x0
#define HPCB_TOKEN_CBS_CMN_PSF_CONTROL_VALUE                 0x0
#define HPCB_TOKEN_CBS_CMN_POST_COMPLETE_PIN_CTRL_VALUE      0x00001D00  //Bit31:28-reserve, Bit27:24-reserve,Bit:23:8-Gpio,Bit7:4-reserve,Bit3:0-OutptLevel
#define HPCB_TOKEN_CBS_CMN_PSP_LOG_CATEGORY_VALUE            0x1
#define HPCB_TOKEN_CBS_CMN_PSP_LOG_LEVEL_VALUE               0x03
#define HPCB_TOKEN_CBS_CMN_MEM_EYE_TEST_VALUE                0x00
#define HPCB_TOKEN_CBS_CMN_AUTOREFFINEGRANMODE_VALUE         0x01
#define HPCB_TOKEN_CBS_CMN_CONSOLE_OUT_SERIAL_PORT_VALUE     0x1
#define HPCB_TOKEN_CBS_CMN_QOS_CONTROL_VALUE                 0x0
#define HPCB_TOKEN_CBS_CMN_SUBCHNL_INTLV_BIT_VALUE           0x0
#define HPCB_TOKEN_CBS_CMN_MCA_BANK_CTL_VALUE                3
#define HPCB_TOKEN_CBS_CMN_BIOS_SPI_SPEED_MODE_VALUE         0xf

//
// Memory CMN Token Attributes Data
//
#define HPCB_CBS_CMN_DEF_ATRIBS_AUTOGEN \
  { HPCB_TIME_POINT_ANY, HPCB_TOKEN_CBS_CMN_CPU_CSV_ASID_SPACE_LIMIT, sizeof (UINT32) - 1, 0 }, \
  { HPCB_TIME_POINT_ANY, HPCB_TOKEN_CBS_CMN_MEM_MBIST_EN, sizeof (UINT8) - 1, 0 }, \
  { HPCB_TIME_POINT_ANY, HPCB_TOKEN_CBS_CMN_MEM_MBIST_SUB_TEST, sizeof (UINT8) - 1, 0 }, \
  { HPCB_TIME_POINT_ANY, HPCB_TOKEN_CBS_CMN_CLDOVDD_PVOLTAGE, sizeof (UINT32) - 1, 0 }, \
  { HPCB_TIME_POINT_ANY, HPCB_TOKEN_CBS_CMN_DJ_CLDO_VDDP_CTL, sizeof (UINT8) - 1, 0 }, \
  { HPCB_TIME_POINT_ANY, HPCB_TOKEN_CBS_CMN_DJ_CLDOVDD_PVOLTAGE, sizeof (UINT32) - 1, 0 }, \
  { HPCB_TIME_POINT_ANY, HPCB_TOKEN_CBS_CMN_EM_CLDO_VDDP_CTL, sizeof (UINT8) - 1, 0 }, \
  { HPCB_TIME_POINT_ANY, HPCB_TOKEN_CBS_CMN_EM_CLDOVDD_PVOLTAGE, sizeof (UINT32) - 1, 0 }, \
  { HPCB_TIME_POINT_ANY, HPCB_TOKEN_CBS_CMN_CDD_CLDO_VDDP_CTL, sizeof (UINT8) - 1, 0 }, \
  { HPCB_TIME_POINT_ANY, HPCB_TOKEN_CBS_CMN_CDD_CLDOVDD_PVOLTAGE, sizeof (UINT32) - 1, 0 }, \
  { HPCB_TIME_POINT_ANY, HPCB_TOKEN_CBS_CMN_CLDO_VDDM_CTL, sizeof (UINT8) - 1, 0 }, \
  { HPCB_TIME_POINT_ANY, HPCB_TOKEN_CBS_CMN_CLDOVDD_MVOLTAGE, sizeof (UINT32) - 1, 0 }, \
  { HPCB_TIME_POINT_ANY, HPCB_TOKEN_CBS_CMN_GNB_XHMI_PHY_RATE_CFG, sizeof (UINT8) - 1, 0 }, \
  { HPCB_TIME_POINT_ANY, HPCB_TOKEN_CBS_CMN_GNB_HMI_PHY_RATE_CFG, sizeof (UINT8) - 1, 0 }, \
  { HPCB_TIME_POINT_ANY, HPCB_TOKEN_CBS_CMN_FCH_CONSOLE_OUT_DIE_TYPE,    sizeof (UINT8) - 1, 0 },\
  { HPCB_TIME_POINT_ANY, HPCB_TOKEN_CBS_CMN_FCH_CONSOLE_OUT_SOCKET_ID,   sizeof (UINT8) - 1, 0 },\
  { HPCB_TIME_POINT_ANY, HPCB_TOKEN_CBS_CMN_FCH_CONSOLE_OUT_IOD_ID,      sizeof (UINT8) - 1, 0 },\
  { HPCB_TIME_POINT_ANY, HPCB_TOKEN_CBS_CMN_FCH_CONSOLE_OUT_CDD_ID,      sizeof (UINT8) - 1, 0 },\
  { HPCB_TIME_POINT_ANY, HPCB_TOKEN_CBS_CMN_FCH_CONSOLE_OUT_ENABLE,     sizeof (UINT8) - 1, 0 },\
  { HPCB_TIME_POINT_ANY, HPCB_TOKEN_CBS_CMN_TPCM_CONTROL,               sizeof (UINT8) - 1, 0 },\
  { HPCB_TIME_POINT_ANY, HPCB_TOKEN_CBS_CMN_PSF_CONTROL,                sizeof (UINT8) - 1, 0 },\
  { HPCB_TIME_POINT_ANY, HPCB_TOKEN_CBS_CMN_POST_COMPLETE_PIN_CTRL,     sizeof (UINT32) - 1, 0 },\
  { HPCB_TIME_POINT_ANY, HPCB_TOKEN_CBS_CMN_PSP_LOG_CATEGORY,           sizeof (UINT8) - 1, 0 },\
  { HPCB_TIME_POINT_ANY, HPCB_TOKEN_CBS_CMN_PSP_LOG_LEVEL,              sizeof (UINT8) - 1, 0 },\
  { HPCB_TIME_POINT_ANY, HPCB_TOKEN_CBS_CMN_MEM_EYE_TEST,               sizeof (UINT8) - 1, 0 },\
  { HPCB_TIME_POINT_ANY, HPCB_TOKEN_CBS_CMN_AUTOREFFINEGRANMODE,        sizeof (UINT8) - 1, 0 },\
  { HPCB_TIME_POINT_ANY, HPCB_TOKEN_CBS_CMN_CONSOLE_OUT_SERIAL_PORT,    sizeof (UINT8) - 1, 0 },\
  { HPCB_TIME_POINT_ANY, HPCB_TOKEN_CBS_CMN_QOS,                        sizeof (UINT8) - 1, 0 },\
  { HPCB_TIME_POINT_ANY, HPCB_TOKEN_CBS_CMN_SUBCHNL_INTLV_BIT,          sizeof (UINT8) - 1, 0 },\
  { HPCB_TIME_POINT_ANY, HPCB_TOKEN_CBS_CMN_MCA_BANK_CTL,               sizeof (UINT8) - 1, 0 },\
  { HPCB_TIME_POINT_ANY, HPCB_TOKEN_CBS_CMN_BIOS_SPI_SPEED_MODE,        sizeof (UINT8) - 1, 0 },\

//
// Memory CMN Value
//
#define HPCB_CBS_CMN_DEF_VALUES_AUTOGEN \
  BSU32 (HPCB_TOKEN_CBS_CMN_CPU_CSV_ASID_SPACE_LIMIT_VALUE), \
  BSU08 (HPCB_TOKEN_CBS_CMN_MEM_MBIST_EN_VALUE), \
  BSU08 (HPCB_TOKEN_CBS_CMN_MEM_MBIST_SUB_TEST_VALUE), \
  BSU32 (HPCB_TOKEN_CBS_CMN_CLDOVDD_PVOLTAGE_VALUE), \
  BSU08 (HPCB_TOKEN_CBS_CMN_DJ_CLDO_VDDP_CTL_VALUE), \
  BSU32 (HPCB_TOKEN_CBS_CMN_DJ_CLDOVDD_PVOLTAGE_VALUE), \
  BSU08 (HPCB_TOKEN_CBS_CMN_EM_CLDO_VDDP_CTL_VALUE), \
  BSU32 (HPCB_TOKEN_CBS_CMN_EM_CLDOVDD_PVOLTAGE_VALUE), \
  BSU08 (HPCB_TOKEN_CBS_CMN_CDD_CLDO_VDDP_CTL_VALUE), \
  BSU32 (HPCB_TOKEN_CBS_CMN_CDD_CLDOVDD_PVOLTAGE_VALUE), \
  BSU08 (HPCB_TOKEN_CBS_CMN_CLDO_VDDM_CTL_VALUE), \
  BSU32 (HPCB_TOKEN_CBS_CMN_CLDOVDD_MVOLTAGE_VALUE), \
  BSU08 (HPCB_TOKEN_CBS_CMN_GNB_XHMI_PHY_RATE_CFG_VALUE), \
  BSU08 (HPCB_TOKEN_CBS_CMN_GNB_HMI_PHY_RATE_CFG_VALUE), \
  BSU08 (HPCB_TOKEN_CBS_CMN_FCH_CONSOLE_OUT_DIE_TYPE_VALUE), \
  BSU08 (HPCB_TOKEN_CBS_CMN_FCH_CONSOLE_OUT_SOCKET_ID_VALUE), \
  BSU08 (HPCB_TOKEN_CBS_CMN_FCH_CONSOLE_OUT_IOD_ID_VALUE), \
  BSU08 (HPCB_TOKEN_CBS_CMN_FCH_CONSOLE_OUT_CDD_ID_VALUE), \
  BSU08 (HPCB_TOKEN_CBS_CMN_FCH_CONSOLE_OUT_ENABLE_VALUE), \
  BSU08 (HPCB_TOKEN_CBS_CMN_TPCM_CONTROL_VALUE), \
  BSU08 (HPCB_TOKEN_CBS_CMN_PSF_CONTROL_VALUE), \
  BSU32 (HPCB_TOKEN_CBS_CMN_POST_COMPLETE_PIN_CTRL_VALUE), \
  BSU08 (HPCB_TOKEN_CBS_CMN_PSP_LOG_CATEGORY_VALUE), \
  BSU08 (HPCB_TOKEN_CBS_CMN_PSP_LOG_LEVEL_VALUE), \
  BSU08 (HPCB_TOKEN_CBS_CMN_MEM_EYE_TEST_VALUE), \
  BSU08 (HPCB_TOKEN_CBS_CMN_AUTOREFFINEGRANMODE_VALUE), \
  BSU08 (HPCB_TOKEN_CBS_CMN_CONSOLE_OUT_SERIAL_PORT_VALUE), \
  BSU08 (HPCB_TOKEN_CBS_CMN_QOS_CONTROL_VALUE), \
  BSU08 (HPCB_TOKEN_CBS_CMN_SUBCHNL_INTLV_BIT_VALUE), \
  BSU08 (HPCB_TOKEN_CBS_CMN_MCA_BANK_CTL_VALUE), \
  BSU08 (HPCB_TOKEN_CBS_CMN_BIOS_SPI_SPEED_MODE_VALUE), \

//
// Memory DBG Token Attributes Data
//
#define HPCB_CBS_DBG_DEF_ATRIBS_AUTOGEN

//
// Memory DBG Value
//
#define HPCB_CBS_DBG_DEF_VALUE_AUTOGEN

#endif //_HPCB_AUTOGEN_SAT_H_
