////////////////////////////////////////////////////////////////////////////////
/// Copyright 2020 HYGON, INC. All Rights Reserved.
/// This file was generated by hgt xgmitxeqtune. Do not modify.
////////////////////////////////////////////////////////////////////////////////

SL1R2_MAKE_TX_EQ_FREQ_TABLE_COMPACT(XGMI_TX_EQ_SPEED_107, SOC_GEN_1, SOC_SL1R2,
    MAKE_TX_EQ_LIST_COMPACT(MAKE_TX_EQ_SOCKET0_DIE0_EACH_LANES_COMPACT(),
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane  0
        MAKE_TX_EQ_LANE_DATA( 31, 36,  0 ), // lane  1
        MAKE_TX_EQ_LANE_DATA( 30, 28, 12 ), // lane  2
        MAKE_TX_EQ_LANE_DATA( 32, 28,  4 ), // lane  3
        MAKE_TX_EQ_LANE_DATA( 31, 36,  0 ), // lane  4
        MAKE_TX_EQ_LANE_DATA( 30, 32,  8 ), // lane  5
        MAKE_TX_EQ_LANE_DATA( 31, 32,  4 ), // lane  6
        MAKE_TX_EQ_LANE_DATA( 31, 36,  0 ), // lane  7
        MAKE_TX_EQ_LANE_DATA( 32, 28,  4 ), // lane  8
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane  9
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane 10
        MAKE_TX_EQ_LANE_DATA( 31, 32,  4 ), // lane 11
        MAKE_TX_EQ_LANE_DATA( 32, 28,  4 ), // lane 12
        MAKE_TX_EQ_LANE_DATA( 32, 28,  4 ), // lane 13
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane 14
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ) // lane 15
    ),
    MAKE_TX_EQ_LIST_COMPACT(MAKE_TX_EQ_SOCKET0_DIE1_EACH_LANES_COMPACT(),
        MAKE_TX_EQ_LANE_DATA( 30, 40,  0 ), // lane  0
        MAKE_TX_EQ_LANE_DATA( 31, 36,  0 ), // lane  1
        MAKE_TX_EQ_LANE_DATA( 31, 32,  4 ), // lane  2
        MAKE_TX_EQ_LANE_DATA( 31, 32,  4 ), // lane  3
        MAKE_TX_EQ_LANE_DATA( 30, 36,  4 ), // lane  4
        MAKE_TX_EQ_LANE_DATA( 31, 32,  4 ), // lane  5
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane  6
        MAKE_TX_EQ_LANE_DATA( 31, 36,  0 ), // lane  7
        MAKE_TX_EQ_LANE_DATA( 31, 32,  4 ), // lane  8
        MAKE_TX_EQ_LANE_DATA( 31, 36,  0 ), // lane  9
        MAKE_TX_EQ_LANE_DATA( 31, 32,  4 ), // lane 10
        MAKE_TX_EQ_LANE_DATA( 31, 32,  4 ), // lane 11
        MAKE_TX_EQ_LANE_DATA( 31, 36,  0 ), // lane 12
        MAKE_TX_EQ_LANE_DATA( 31, 36,  0 ), // lane 13
        MAKE_TX_EQ_LANE_DATA( 31, 36,  0 ), // lane 14
        MAKE_TX_EQ_LANE_DATA( 31, 32,  4 ) // lane 15
    ),
    MAKE_TX_EQ_LIST_COMPACT(MAKE_TX_EQ_SOCKET1_DIE0_EACH_LANES_COMPACT(),
        MAKE_TX_EQ_LANE_DATA( 31, 32,  4 ), // lane  0
        MAKE_TX_EQ_LANE_DATA( 31, 32,  4 ), // lane  1
        MAKE_TX_EQ_LANE_DATA( 30, 28, 12 ), // lane  2
        MAKE_TX_EQ_LANE_DATA( 32, 28,  4 ), // lane  3
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane  4
        MAKE_TX_EQ_LANE_DATA( 30, 32,  8 ), // lane  5
        MAKE_TX_EQ_LANE_DATA( 32, 24,  8 ), // lane  6
        MAKE_TX_EQ_LANE_DATA( 30, 36,  4 ), // lane  7
        MAKE_TX_EQ_LANE_DATA( 31, 32,  4 ), // lane  8
        MAKE_TX_EQ_LANE_DATA( 30, 36,  4 ), // lane  9
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane 10
        MAKE_TX_EQ_LANE_DATA( 31, 32,  4 ), // lane 11
        MAKE_TX_EQ_LANE_DATA( 30, 36,  4 ), // lane 12
        MAKE_TX_EQ_LANE_DATA( 30, 32,  8 ), // lane 13
        MAKE_TX_EQ_LANE_DATA( 31, 32,  4 ), // lane 14
        MAKE_TX_EQ_LANE_DATA( 31, 32,  4 ) // lane 15
    ),
    MAKE_TX_EQ_LIST_COMPACT(MAKE_TX_EQ_SOCKET1_DIE1_EACH_LANES_COMPACT(),
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane  0
        MAKE_TX_EQ_LANE_DATA( 34, 20,  4 ), // lane  1
        MAKE_TX_EQ_LANE_DATA( 33, 24,  4 ), // lane  2
        MAKE_TX_EQ_LANE_DATA( 33, 24,  4 ), // lane  3
        MAKE_TX_EQ_LANE_DATA( 32, 24,  8 ), // lane  4
        MAKE_TX_EQ_LANE_DATA( 32, 28,  4 ), // lane  5
        MAKE_TX_EQ_LANE_DATA( 34, 24,  0 ), // lane  6
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane  7
        MAKE_TX_EQ_LANE_DATA( 32, 28,  4 ), // lane  8
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane  9
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane 10
        MAKE_TX_EQ_LANE_DATA( 32, 28,  4 ), // lane 11
        MAKE_TX_EQ_LANE_DATA( 31, 32,  4 ), // lane 12
        MAKE_TX_EQ_LANE_DATA( 31, 32,  4 ), // lane 13
        MAKE_TX_EQ_LANE_DATA( 32, 28,  4 ), // lane 14
        MAKE_TX_EQ_LANE_DATA( 31, 28,  8 ) // lane 15
    )
),

SL1R2_MAKE_TX_EQ_FREQ_TABLE_COMPACT(XGMI_TX_EQ_SPEED_107, SOC_GEN_2, SOC_SL1R2,
    MAKE_TX_EQ_LIST_COMPACT(MAKE_TX_EQ_SOCKET0_DIE0_EACH_LANES_COMPACT(),
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane  0
        MAKE_TX_EQ_LANE_DATA( 31, 36,  0 ), // lane  1
        MAKE_TX_EQ_LANE_DATA( 30, 28, 12 ), // lane  2
        MAKE_TX_EQ_LANE_DATA( 32, 28,  4 ), // lane  3
        MAKE_TX_EQ_LANE_DATA( 31, 36,  0 ), // lane  4
        MAKE_TX_EQ_LANE_DATA( 30, 32,  8 ), // lane  5
        MAKE_TX_EQ_LANE_DATA( 31, 32,  4 ), // lane  6
        MAKE_TX_EQ_LANE_DATA( 31, 36,  0 ), // lane  7
        MAKE_TX_EQ_LANE_DATA( 32, 28,  4 ), // lane  8
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane  9
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane 10
        MAKE_TX_EQ_LANE_DATA( 31, 32,  4 ), // lane 11
        MAKE_TX_EQ_LANE_DATA( 32, 28,  4 ), // lane 12
        MAKE_TX_EQ_LANE_DATA( 32, 28,  4 ), // lane 13
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane 14
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ) // lane 15
    ),
    MAKE_TX_EQ_LIST_COMPACT(MAKE_TX_EQ_SOCKET0_DIE1_EACH_LANES_COMPACT(),
        MAKE_TX_EQ_LANE_DATA( 30, 40,  0 ), // lane  0
        MAKE_TX_EQ_LANE_DATA( 31, 36,  0 ), // lane  1
        MAKE_TX_EQ_LANE_DATA( 31, 32,  4 ), // lane  2
        MAKE_TX_EQ_LANE_DATA( 31, 32,  4 ), // lane  3
        MAKE_TX_EQ_LANE_DATA( 30, 36,  4 ), // lane  4
        MAKE_TX_EQ_LANE_DATA( 31, 32,  4 ), // lane  5
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane  6
        MAKE_TX_EQ_LANE_DATA( 31, 36,  0 ), // lane  7
        MAKE_TX_EQ_LANE_DATA( 31, 32,  4 ), // lane  8
        MAKE_TX_EQ_LANE_DATA( 31, 36,  0 ), // lane  9
        MAKE_TX_EQ_LANE_DATA( 31, 32,  4 ), // lane 10
        MAKE_TX_EQ_LANE_DATA( 31, 32,  4 ), // lane 11
        MAKE_TX_EQ_LANE_DATA( 31, 36,  0 ), // lane 12
        MAKE_TX_EQ_LANE_DATA( 31, 36,  0 ), // lane 13
        MAKE_TX_EQ_LANE_DATA( 31, 36,  0 ), // lane 14
        MAKE_TX_EQ_LANE_DATA( 31, 32,  4 ) // lane 15
    ),
    MAKE_TX_EQ_LIST_COMPACT(MAKE_TX_EQ_SOCKET1_DIE0_EACH_LANES_COMPACT(),
        MAKE_TX_EQ_LANE_DATA( 31, 32,  4 ), // lane  0
        MAKE_TX_EQ_LANE_DATA( 31, 32,  4 ), // lane  1
        MAKE_TX_EQ_LANE_DATA( 30, 28, 12 ), // lane  2
        MAKE_TX_EQ_LANE_DATA( 32, 28,  4 ), // lane  3
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane  4
        MAKE_TX_EQ_LANE_DATA( 30, 32,  8 ), // lane  5
        MAKE_TX_EQ_LANE_DATA( 32, 24,  8 ), // lane  6
        MAKE_TX_EQ_LANE_DATA( 30, 36,  4 ), // lane  7
        MAKE_TX_EQ_LANE_DATA( 31, 32,  4 ), // lane  8
        MAKE_TX_EQ_LANE_DATA( 30, 36,  4 ), // lane  9
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane 10
        MAKE_TX_EQ_LANE_DATA( 31, 32,  4 ), // lane 11
        MAKE_TX_EQ_LANE_DATA( 30, 36,  4 ), // lane 12
        MAKE_TX_EQ_LANE_DATA( 30, 32,  8 ), // lane 13
        MAKE_TX_EQ_LANE_DATA( 31, 32,  4 ), // lane 14
        MAKE_TX_EQ_LANE_DATA( 31, 32,  4 ) // lane 15
    ),
    MAKE_TX_EQ_LIST_COMPACT(MAKE_TX_EQ_SOCKET1_DIE1_EACH_LANES_COMPACT(),
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane  0
        MAKE_TX_EQ_LANE_DATA( 34, 20,  4 ), // lane  1
        MAKE_TX_EQ_LANE_DATA( 33, 24,  4 ), // lane  2
        MAKE_TX_EQ_LANE_DATA( 33, 24,  4 ), // lane  3
        MAKE_TX_EQ_LANE_DATA( 32, 24,  8 ), // lane  4
        MAKE_TX_EQ_LANE_DATA( 32, 28,  4 ), // lane  5
        MAKE_TX_EQ_LANE_DATA( 34, 24,  0 ), // lane  6
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane  7
        MAKE_TX_EQ_LANE_DATA( 32, 28,  4 ), // lane  8
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane  9
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane 10
        MAKE_TX_EQ_LANE_DATA( 32, 28,  4 ), // lane 11
        MAKE_TX_EQ_LANE_DATA( 31, 32,  4 ), // lane 12
        MAKE_TX_EQ_LANE_DATA( 31, 32,  4 ), // lane 13
        MAKE_TX_EQ_LANE_DATA( 32, 28,  4 ), // lane 14
        MAKE_TX_EQ_LANE_DATA( 31, 28,  8 ) // lane 15
    )
),
