/* $NoKeywords:$ */

/**
 * @file
 *
 * HPCB DXE Driver
 *
 *
 * @xrefitem bom "File Content Label" "Release Content"
 * @e project:      HGPI
 * @e sub-project:  HPCB
 *
 */
/*****************************************************************************
 *
 *
 * Copyright 2016 - 2023 CHENGDU HAIGUANG IC DESIGN CO., LTD. All Rights Reserved.
 *
 * HYGON is granting you permission to use this software (the Materials)
 * pursuant to the terms and conditions of your Software License Agreement
 * with HYGON.  This header does *NOT* give you permission to use the Materials
 * or any rights under HYGON's intellectual property.  Your use of any portion
 * of these Materials shall constitute your acceptance of those terms and
 * conditions.  If you do not agree to the terms and conditions of the Software
 * License Agreement, please do not use any portion of these Materials.
 *
 * CONFIDENTIALITY:  The Materials and all other information, identified as
 * confidential and provided to you by HYGON shall be kept confidential in
 * accordance with the terms and conditions of the Software License Agreement.
 *
 * LIMITATION OF LIABILITY: THE MATERIALS AND ANY OTHER RELATED INFORMATION
 * PROVIDED TO YOU BY HYGON ARE PROVIDED "AS IS" WITHOUT ANY EXPRESS OR IMPLIED
 * WARRANTY OF ANY KIND, INCLUDING BUT NOT LIMITED TO WARRANTIES OF
 * MERCHANTABILITY, NONINFRINGEMENT, TITLE, FITNESS FOR ANY PARTICULAR PURPOSE,
 * OR WARRANTIES ARISING FROM CONDUCT, COURSE OF DEALING, OR USAGE OF TRADE.
 * IN NO EVENT SHALL HYGON OR ITS LICENSORS BE LIABLE FOR ANY DAMAGES WHATSOEVER
 * (INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF PROFITS, BUSINESS
 * INTERRUPTION, OR LOSS OF INFORMATION) ARISING OUT OF HYGON'S NEGLIGENCE,
 * GROSS NEGLIGENCE, THE USE OF OR INABILITY TO USE THE MATERIALS OR ANY OTHER
 * RELATED INFORMATION PROVIDED TO YOU BY HYGON, EVEN IF HYGON HAS BEEN ADVISED OF
 * THE POSSIBILITY OF SUCH DAMAGES.  BECAUSE SOME JURISDICTIONS PROHIBIT THE
 * EXCLUSION OR LIMITATION OF LIABILITY FOR CONSEQUENTIAL OR INCIDENTAL DAMAGES,
 * THE ABOVE LIMITATION MAY NOT APPLY TO YOU.
 *
 * HYGON does not assume any responsibility for any errors which may appear in
 * the Materials or any other related information provided to you by HYGON, or
 * result from use of the Materials or any related information.
 *
 * You agree that you will not reverse engineer or decompile the Materials.
 *
 * NO SUPPORT OBLIGATION: HYGON is not obligated to furnish, support, or make any
 * further information, software, technical information, know-how, or show-how
 * available to you.  Additionally, HYGON retains the right to modify the
 * Materials at any time, without notice, and is not obligated to provide such
 * modified Materials to you.
 *
 *
 ******************************************************************************
 */
#include "HGPI.h"
#include <HPCB.h>
#include "HpcbCommon.h"
#include <Library/IdsLib.h>
#include <Filecode.h>

#define FILECODE  PSP_HPCB_TOKENS_CBS_EXT_TOKENS_FILECODE

//
// HPCB CBS Token ID definitions
//
TOKEN_PAIR  CbsExtTokenPair[] = {
  { HPCB_ID_CBS_DF_CMN_HMI_ENCRYPTION,                HPCB_TOKEN_CBS_DF_CMN_HMI_ENCRYPTION                },
  { HPCB_ID_CBS_DF_CMN_X_HMI_ENCRYPTION,              HPCB_TOKEN_CBS_DF_CMN_X_HMI_ENCRYPTION              },
  { HPCB_ID_CBS_DF_CMN_CC6_MEM_ENCRYPTION,            HPCB_TOKEN_CBS_DF_CMN_CC6_MEM_ENCRYPTION            },
  { HPCB_ID_CBS_DF_CMN_CC6_ALLOCATION_SCHEME,         HPCB_TOKEN_CBS_DF_CMN_CC6_ALLOCATION_SCHEME         },
  { HPCB_ID_CBS_DF_CMN_SYS_PROBE_FILTER,              HPCB_TOKEN_CBS_DF_CMN_SYS_PROBE_FILTER              },
  { HPCB_ID_CBS_DF_CMN_MEM_INTLV,                     HPCB_TOKEN_CBS_DF_CMN_MEM_INTLV                     },
  { HPCB_ID_CBS_DF_CMN_MEM_INTLV_SIZE,                HPCB_TOKEN_CBS_DF_CMN_MEM_INTLV_SIZE                },
  { HPCB_ID_CBS_DF_CMN_CHNL_INTLV_HASH,               HPCB_TOKEN_CBS_DF_CMN_CHNL_INTLV_HASH               },
  { HPCB_ID_CBS_CMN_MEM_MAPPING_BANK_INTERLEAVE_DDR5, HPCB_TOKEN_CBS_CMN_MEM_MAPPING_BANK_INTERLEAVE_DDR5 },
  { HPCB_ID_CBS_CMN_MEM_CTRLLER_BANK_GROUP_SWAP_DDR5, HPCB_TOKEN_CBS_CMN_MEM_CTRLLER_BANK_GROUP_SWAP_DDR5 },
  { HPCB_ID_CBS_CMN_MEM_CTRLLER_BANK_SWIZZLE_DDR5,    HPCB_TOKEN_CBS_CMN_MEM_CTRLLER_BANK_SWIZZLE_DDR5    },
  { HPCB_ID_CBS_CMN_MEM_ADDRESS_HASHING_DDR5,         HPCB_TOKEN_CBS_CMN_MEM_ADDRESS_HASHING_DDR5         },
  { HPCB_ID_CBS_CMN_MEM_SPEED_DDR5,                   HPCB_TOKEN_CBS_CMN_MEM_SPEED_DDR5                   },
  { HPCB_ID_CBS_CMN_MEM_TIMING_TCL_DDR5,              HPCB_TOKEN_CBS_CMN_MEM_TIMING_TCL_DDR5              },
  { HPCB_ID_CBS_CMN_MEM_TIMING_TRCDRD_DDR5,           HPCB_TOKEN_CBS_CMN_MEM_TIMING_TRCDRD_DDR5           },
  { HPCB_ID_CBS_CMN_MEM_TIMING_TRCDWR_DDR5,           HPCB_TOKEN_CBS_CMN_MEM_TIMING_TRCDWR_DDR5           },
  { HPCB_ID_CBS_CMN_MEM_TIMING_TRP_DDR5,              HPCB_TOKEN_CBS_CMN_MEM_TIMING_TRP_DDR5              },
  { HPCB_ID_CBS_CMN_MEM_TIMING_TRAS_DDR5,             HPCB_TOKEN_CBS_CMN_MEM_TIMING_TRAS_DDR5             },
  { HPCB_ID_CBS_CMN_MEM_DATA_POISONING_DDR5,          HPCB_TOKEN_CBS_CMN_MEM_DATA_POISONING_DDR5          },
  { HPCB_ID_CBS_CMN_MEM_ADDRESS_HASH_BANK_DDR5,       HPCB_TOKEN_CBS_CMN_MEM_ADDRESS_HASH_BANK_DDR5       },
  { HPCB_ID_CBS_CMN_MEM_ADDRESS_HASH_CS_DDR5,         HPCB_TOKEN_CBS_CMN_MEM_ADDRESS_HASH_CS_DDR5         },
  { HPCB_ID_CBS_CMN_MEM_TSME_DDR5,                    HPCB_TOKEN_CBS_CMN_MEM_TSME_DDR5                    },
  { HPCB_ID_CBS_CMN_MEM_OVERCLOCK_DDR5,               HPCB_TOKEN_CBS_CMN_MEM_OVERCLOCK_DDR5               },
  { HPCB_ID_CBS_CMN_GNB_GFX_UMA_MODE,                 HPCB_TOKEN_CBS_CMN_GNB_GFX_UMA_MODE                 },
  { HPCB_ID_CBS_CMN_GNB_GFX_UMA_VERSION,              HPCB_TOKEN_CBS_CMN_GNB_GFX_UMA_VERSION              },
  { HPCB_ID_CBS_CMN_GNB_GFX_DISPLAY_RESOLUTION,       HPCB_TOKEN_CBS_CMN_GNB_GFX_DISPLAY_RESOLUTION       },
  { HPCB_ID_CBS_CMN_GNB_GFX_UMA_FRAME_BUFFER_SIZE,    HPCB_TOKEN_CBS_CMN_GNB_GFX_UMA_FRAME_BUFFER_SIZE    },
  { HPCB_ID_CBS_CMN_CPU_CSV_ASID_SPACE_LIMIT,         HPCB_TOKEN_CBS_CMN_CPU_CSV_ASID_SPACE_LIMIT         },
  { HPCB_ID_CBS_CMN_MEM_SPD_READ_OPTIMIZATION_DDR5,   HPCB_TOKEN_CBS_CMN_MEM_SPD_READ_OPTIMIZATION_DDR5   },
  { HPCB_ID_CBS_CMN_MEM_MBIST_EN,                     HPCB_TOKEN_CBS_CMN_MEM_MBIST_EN                     },
  { HPCB_ID_CBS_CMN_MEM_MBIST_TESTMODE,               HPCB_TOKEN_CBS_CMN_MEM_MBIST_SUB_TEST               },
  { HPCB_ID_CBS_DF_CMN_MEM_CLEAR,                     HPCB_TOKEN_CBS_DF_CMN_MEM_CLEAR                     },
  { HPCB_ID_CBS_CMN_MEM_TIMING_TRC_CTRL_DDR5,         HPCB_TOKEN_CBS_CMN_MEM_TIMING_TRC_CTRL_DDR5         },
  { HPCB_ID_CBS_CMN_MEM_TIMING_TRC_DDR5,              HPCB_TOKEN_CBS_CMN_MEM_TIMING_TRC_DDR5              },
  { HPCB_ID_CBS_CMN_MEM_TIMING_TRRD_S_DDR5,           HPCB_TOKEN_CBS_CMN_MEM_TIMING_TRRD_S_DDR5           },
  { HPCB_ID_CBS_CMN_MEM_TIMING_TRRD_L_DDR5,           HPCB_TOKEN_CBS_CMN_MEM_TIMING_TRRD_L_DDR5           },
  { HPCB_ID_CBS_CMN_MEM_TIMING_TFAW_CTRL_DDR5,        HPCB_TOKEN_CBS_CMN_MEM_TIMING_TFAW_CTRL_DDR5        },
  { HPCB_ID_CBS_CMN_MEM_TIMING_TFAW_DDR5,             HPCB_TOKEN_CBS_CMN_MEM_TIMING_TFAW_DDR5             },
  { HPCB_ID_CBS_CMN_MEM_TIMING_TWTR_S_DDR5,           HPCB_TOKEN_CBS_CMN_MEM_TIMING_TWTR_S_DDR5           },
  { HPCB_ID_CBS_CMN_MEM_TIMING_TWTR_L_DDR5,           HPCB_TOKEN_CBS_CMN_MEM_TIMING_TWTR_L_DDR5           },
  { HPCB_ID_CBS_CMN_MEM_TIMING_TWR_CTRL_DDR5,         HPCB_TOKEN_CBS_CMN_MEM_TIMING_TWR_CTRL_DDR5         },
  { HPCB_ID_CBS_CMN_MEM_TIMING_TWR_DDR5,              HPCB_TOKEN_CBS_CMN_MEM_TIMING_TWR_DDR5              },
  { HPCB_ID_CBS_CMN_MEM_TIMING_TRCPAGE_CTRL_DDR5,     HPCB_TOKEN_CBS_CMN_MEM_TIMING_TRCPAGE_CTRL_DDR5     },
  { HPCB_ID_CBS_CMN_MEM_TIMING_TRCPAGE_DDR5,          HPCB_TOKEN_CBS_CMN_MEM_TIMING_TRCPAGE_DDR5          },
  { HPCB_ID_CBS_CMN_MEM_TIMING_TRDRD_SC_L_CTRL_DDR5,  HPCB_TOKEN_CBS_CMN_MEM_TIMING_TRDRD_SC_L_CTRL_DDR5  },
  { HPCB_ID_CBS_CMN_MEM_TIMING_TRDRD_SC_L_DDR5,       HPCB_TOKEN_CBS_CMN_MEM_TIMING_TRDRD_SC_L_DDR5       },
  { HPCB_ID_CBS_CMN_MEM_TIMING_TWRWR_SC_L_CTRL_DDR5,  HPCB_TOKEN_CBS_CMN_MEM_TIMING_TWRWR_SC_L_CTRL_DDR5  },
  { HPCB_ID_CBS_CMN_MEM_TIMING_TWRWR_SC_L_DDR5,       HPCB_TOKEN_CBS_CMN_MEM_TIMING_TWRWR_SC_L_DDR5       },
  { HPCB_ID_CBS_CMN_MEM_TIMING_TRFC_CTRL_DDR5,        HPCB_TOKEN_CBS_CMN_MEM_TIMING_TRFC_CTRL_DDR5        },
  { HPCB_ID_CBS_CMN_MEM_TIMING_TRFC_DDR5,             HPCB_TOKEN_CBS_CMN_MEM_TIMING_TRFC_DDR5             },
  { HPCB_ID_CBS_CMN_MEM_TIMING_TRFC2_CTRL_DDR5,       HPCB_TOKEN_CBS_CMN_MEM_TIMING_TRFC2_CTRL_DDR5       },
  { HPCB_ID_CBS_CMN_MEM_TIMING_TRFC2_DDR5,            HPCB_TOKEN_CBS_CMN_MEM_TIMING_TRFC2_DDR5            },
  { HPCB_ID_CBS_CMN_MEM_TIMING_TRFC4_CTRL_DDR5,       HPCB_TOKEN_CBS_CMN_MEM_TIMING_TRFC4_CTRL_DDR5       },
  { HPCB_ID_CBS_CMN_MEM_TIMING_TRFC4_DDR5,            HPCB_TOKEN_CBS_CMN_MEM_TIMING_TRFC4_DDR5            },
  { HPCB_ID_CBS_CMN_MEM_OVERCLOCK_FAIL_CNT,           HPCB_TOKEN_CBS_CMN_MEM_OVERCLOCK_FAIL_CNT           },
  { HPCB_ID_CBS_CMN_MEM_CTRLLER_PROC_ODT_DDR5,        HPCB_TOKEN_CBS_CMN_MEM_CTRLLER_PROC_ODT_DDR5        },
  { HPCB_ID_CBS_CMN_MEM_TIMING_TRDRD_SC_DDR5,         HPCB_TOKEN_CBS_CMN_MEM_TIMING_TRDRD_SC_DDR5         },
  { HPCB_ID_CBS_CMN_MEM_TIMING_TRDRD_SD_DDR5,         HPCB_TOKEN_CBS_CMN_MEM_TIMING_TRDRD_SD_DDR5         },
  { HPCB_ID_CBS_CMN_MEM_TIMING_TRDRD_DD_DDR5,         HPCB_TOKEN_CBS_CMN_MEM_TIMING_TRDRD_DD_DDR5         },
  { HPCB_ID_CBS_CMN_MEM_TIMING_TWRWR_SC_DDR5,         HPCB_TOKEN_CBS_CMN_MEM_TIMING_TWRWR_SC_DDR5         },
  { HPCB_ID_CBS_CMN_MEM_TIMING_TWRWR_SD_DDR5,         HPCB_TOKEN_CBS_CMN_MEM_TIMING_TWRWR_SD_DDR5         },
  { HPCB_ID_CBS_CMN_MEM_TIMING_TWRWR_DD_DDR5,         HPCB_TOKEN_CBS_CMN_MEM_TIMING_TWRWR_DD_DDR5         },
  { HPCB_ID_CBS_CMN_MEM_TIMING_TRDWR_DDR5,            HPCB_TOKEN_CBS_CMN_MEM_TIMING_TRDWR_DDR5            },
  { HPCB_ID_CBS_CMN_MEM_TIMING_TWRRD_DDR5,            HPCB_TOKEN_CBS_CMN_MEM_TIMING_TWRRD_DDR5            },
  { HPCB_ID_CBS_CMN_MEM_TIMING_TRTP_DDR5,             HPCB_TOKEN_CBS_CMN_MEM_TIMING_TRTP_DDR5             },
  { HPCB_ID_CBS_CMN_MEM_TIMING_TCWL_DDR5,             HPCB_TOKEN_CBS_CMN_MEM_TIMING_TCWL_DDR5             },
  { HPCB_ID_CBS_CMN_MEM_DATA_BUS_CONFIG_CTL_DDR5,     HPCB_TOKEN_CBS_CMN_MEM_DATA_BUS_CONFIG_CTL_DDR5     },
  { HPCB_ID_CBS_CMN_MEM_CTRLLER_RTT_NOM_DDR5,         HPCB_TOKEN_CBS_CMN_MEM_CTRLLER_RTT_NOM_DDR5         },
  { HPCB_ID_CBS_CMN_MEM_CTRLLER_RTT_WR_DDR5,          HPCB_TOKEN_CBS_CMN_MEM_CTRLLER_RTT_WR_DDR5          },
  { HPCB_ID_CBS_CMN_MEM_CTRLLER_RTT_PARK_DDR5,        HPCB_TOKEN_CBS_CMN_MEM_CTRLLER_RTT_PARK_DDR5        },
  { HPCB_ID_CBS_CMN_MEM_TIMING_TCKE_DDR5,             HPCB_TOKEN_CBS_CMN_MEM_TIMING_TCKE_DDR5             },
  { HPCB_ID_CBS_CMN_MEM_CTRLLER_DATA_SCRAMBLE_DDR5,   HPCB_TOKEN_CBS_CMN_MEM_CTRLLER_DATA_SCRAMBLE_DDR5   },
};

UINT16
mTranslateCbsExtTokenId (
  IN       UINT16             CommonId
  )
{
  UINT16  i;

  for (i = 0; i < sizeof (CbsExtTokenPair) / sizeof (TOKEN_PAIR); i++) {
    if (CommonId == CbsExtTokenPair[i].HpcbCommonId) {
      return CbsExtTokenPair[i].HpcbToken;
    }
  }

  ASSERT (FALSE);

  return 0xFFFF;
}
