# autogen file, do not edit ...                  
DEFINE BC_NORMAL  = FALSE  
DEFINE BC_TENCENT  = TRUE  
DEFINE BC_INSPUR_ST  = FALSE  
DEFINE UART_SELECTION = 2 
DEFINE TEST_BIOS_VERSION  = 0  
DEFINE BIOS_SIGN_KEY_PATH = ProjectPkg\SignKey 
DEFINE BIOS_FILE_NAME = CS5260H_BIOS_9.03.01_Tencent_20210914D 
DEFINE BIOS_VERSION_NAME = 9.03.01  
